[package]
name = "certval_stores_pbdev"
version = "0.1.0"
edition = "2021"
description = "Development (Purebred dev) trust store for certval"

[dependencies]
certval_stores_core = { path = "../certval_stores_core" }

[features]
default = ["dev"]
# Purebred development environment (DoD Engineering roots).
dev = []
