//! Generated by `certval-store-gen` from `authroot.stl`, published 2026-08-25. Do not edit.
//!
//! The 267 roots this environment carries, in thumbprint order.

/// The trust anchors of this environment, in thumbprint order.
pub(crate) static ROOTS: &[&[u8]] = &[
    include_bytes!("../roots/010C0695A6981914FFBF5FC6B0B695EA29E912A6.der"), // Hellenic Academic and Research Institutions RootCA 2015
    include_bytes!("../roots/022D0582FA88CE140C0679DE7F1410E945D7A56D.der"), // HARICA TLS RSA Root CA 2021
    include_bytes!("../roots/0563B8630D62D75ABBC8AB1E4BDFB5A899B24D43.der"), // DigiCert
    include_bytes!("../roots/06083F593F15A104A069A46BA903D006B7970991.der"), // NetLock Arany (Class Gold) Főtanúsítvány
    include_bytes!("../roots/07E032E020B72C3F192F0628A2593A19A70F069E.der"), // Certum Trusted Network CA
    include_bytes!("../roots/093C61F38B8BDC7D55DF7538020500E125F5C836.der"), // QuoVadis Root CA 2 G3
    include_bytes!("../roots/0AB5C3CD7448B86D711E77A549838B87CE525F7F.der"), // Netrust Root CA 2
    include_bytes!("../roots/0BBEC2272249CB39AADB355C53E38CAE78FFB6FE.der"), // Autoridad de Certificacion Firmaprofesional CIF A62634068
    include_bytes!("../roots/0D44DD8C3C8C1A1A58756481E90F2E2AFFB3D26E.der"), // Amazon Root CA 3
    include_bytes!("../roots/0D9E9AB20765A89ED9CD8DF2C7A63BC77495EF31.der"), // SSL.com Code Signing ECC Root CA 2022
    include_bytes!("../roots/0F36385B811A25C39B314E83CAE9346670CC74B4.der"), // GDCA TrustAUTH R5 ROOT
    include_bytes!("../roots/0FF9407618D3D76A4B98F0A8359E0CFD27ACCCED.der"), // OISTE WISeKey Global Root GB CA
    include_bytes!("../roots/1068BFBEA253BAE0E6E03F34E8C2F1CE2D764B57.der"), // QuoVadis Client RSA 4096 Root G4
    include_bytes!("../roots/1139A49E8484AAF2D90D985EC4741A65DD5D94E2.der"), // GLOBAL CHAMBERSIGN ROOT - 2016
    include_bytes!("../roots/14884E862637B026AF59625C4077EC3529BA9601.der"), // Entrust Root Certification Authority - G4
    include_bytes!("../roots/17F3DE5E9F0F19E98EF61F32266E20C407AE30EE.der"), // DigiCert TLS ECC P384 Root G5
    include_bytes!("../roots/182E1F324F89DFBEFE8889F093C2C4A02B677521.der"), // GlobalSign Secure Mail Root E45
    include_bytes!("../roots/18523B0D0637E4D63ADF23E498FB5B16FB867448.der"), // Atos TrustedRoot Root CA RSA TLS 2021
    include_bytes!("../roots/193C2A76F8CADD84F35BF52EE7AA506657917A38.der"), // Entrust 4K TLS Root CA - 2022
    include_bytes!("../roots/1B8EEA5796291AC939EAB80A811A7373C0937967.der"), // QuoVadis Root CA 1 G3
    include_bytes!("../roots/1CB8A708C90D207901A0B2367FF09565E45324FE.der"), // DigiCert SMIME ECC P384 Root G5
    include_bytes!("../roots/1E6C44DC6473D4819BE89FB237AF4883FC376987.der"), // Entrust P384 EV TLS Root CA - 2022
    include_bytes!("../roots/1E70283209903C9472C79B2C103E8EBB238BEB62.der"), // I.CA Root CA_ECC 12_2016
    include_bytes!("../roots/1F24C630CDA418EF2069FFAD4FDD5F463A1B69AA.der"), // GlobalSign ECC Root CA - R5
    include_bytes!("../roots/1F3F1486B531882802E87B624D420295A0FC721A.der"), // Notarius Root Certificate Authority
    include_bytes!("../roots/1F4914F7D874951DDDAE02C0BEFD3A2D82755185.der"), // QuoVadis Root CA 3
    include_bytes!("../roots/1F5B98F0E3B5F7743CEDE6B0367D32CDF4094167.der"), // D-TRUST BR Root CA 1 2020
    include_bytes!("../roots/204285DCF7EB764195578E136BD4B7D1E98E46A5.der"), // VeriSign
    include_bytes!("../roots/20AFEA8DCB031F0684DF8FFD2598C8B7967FCD3C.der"), // QuoVadis TLS RSA 4096 Root G4
    include_bytes!("../roots/20D80640DF9B25F512253A11EAF7598AEB14B547.der"), // Entrust Root Certification Authority - EC1
    include_bytes!("../roots/225E108F13B93E35B5C4C7BCA6A11F750EAE5037.der"), // QuoVadis Signing RSA 4096 Root G4
    include_bytes!("../roots/23D731FEDC5C8BB97DE6DC8E13B411BD4F24004F.der"), // Halcom Root Certificate Authority
    include_bytes!("../roots/26F993B4ED3D2827B0B94BA7E9151DA38D92E532.der"), // certSIGN ROOT CA G2
    include_bytes!("../roots/2796BAE63F1801E277261BA0D77770028F20EEE4.der"), // Go Daddy Class 2 Certification Authority
    include_bytes!("../roots/28903A635B5280FAE6774C0B6DA7D6BAA64AF2E8.der"), // Agencia Catalana de Certificacio (NIF Q-0801176-I)
    include_bytes!("../roots/28F97816197AFF182518AA44FEC1A0CE5CB64C8A.der"), // UCA Global G2 Root
    include_bytes!("../roots/293621028B20ED02F566C532D1D6ED909F45002F.der"), // AffirmTrust Networking
    include_bytes!("../roots/2A1D6027D94AB10A1C4D915CCD33A0CB3E2D54CB.der"), // GTS Root R4
    include_bytes!("../roots/2B8F1B57330DBBA2D07A6C51F70EE90DDAB9AD8E.der"), // Sectigo
    include_bytes!("../roots/2BB1F53E550C1DC5F1D4E6B76A464B550602AC21.der"), // Atos TrustedRoot 2011
    include_bytes!("../roots/2D0D5214FF9EAD9924017420476E6C852727F543.der"), // Certigna Root CA
    include_bytes!("../roots/2DB070EE7194AF696817DB79CE589FA06B96F787.der"), // D-TRUST BR Root CA 2 2023
    include_bytes!("../roots/2DE16A5677BACA39E1D68C30DCB14ABE22A6179B.der"), // CHAMBERS OF COMMERCE ROOT - 2016
    include_bytes!("../roots/2E03931CD19C3FF5985FB87AADC153EB5DBDF1E3.der"), // AffirmTrust 4K TLS Root CA - 2022
    include_bytes!("../roots/2F686DC8D4E39553ED32938E6357133BB7D9910C.der"), // SSL.com Document Signing RSA Root CA 2022
    include_bytes!("../roots/2F8F364FE1589744215987A52A9AD06995267FB5.der"), // Trustwave Global Certification Authority
    include_bytes!("../roots/3043FA4FF257DCA0C380EE2E58EA78B23FE6BBC1.der"), // emSign ECC Root CA - G3
    include_bytes!("../roots/30D4246F07FFDB91898A0BE9496611EB8C5E46E5.der"), // GTS Root R3
    include_bytes!("../roots/3143649BECCE27ECED3A3F0B8F0DE4E891DDEECA.der"), // TUBITAK Kamu SM SSL Kok Sertifikasi - Surum 1
    include_bytes!("../roots/32D127FA93B1C14C99E24A40BC7F94411B5AACA4.der"), // Atos TrustedRoot Root CA RSA G2 2020
    include_bytes!("../roots/335A7FF00927CF2DF278E2C9192F7A4D5534F80C.der"), // LAWtrust Root Certification Authority 2048
    include_bytes!("../roots/33EA1C7E79CF3166FDB9FA324773FBB78901004F.der"), // Telia EC Email Root CA v3
    include_bytes!("../roots/342CD9D3062DA48C346965297F081EBC2EF68FDC.der"), // Austrian Society for Data Protection GLOBALTRUST Certification Service
    include_bytes!("../roots/3679CA35668772304D30A5FB873B0FA77BB70D54.der"), // VeriSign Universal Root Certification Authority
    include_bytes!("../roots/3753D295FC6D8BC39B375650BFFC821AED504E1A.der"), // ZETES TSP ROOT CA 001
    include_bytes!("../roots/39B46CD5FE8006EBE22F4ABB0833A0AFDBB9DD84.der"), // GlobalSign Root E46
    include_bytes!("../roots/3A44735AE581901F248661461E3B9CC45FF53A1B.der"), // Trustwave
    include_bytes!("../roots/3A4979B40FA841488200B582FBEEB63AAB9919AE.der"), // SI-TRUST Root
    include_bytes!("../roots/3AC5C378345BE1829246ED1786B393917B51F214.der"), // Sectigo Public Email Protection Root E46
    include_bytes!("../roots/3BC49F48F8F373A09C1EBDF85BB1C365C7D811B3.der"), // Japan Certification Services, Inc. SecureSign RootCA11
    include_bytes!("../roots/3CC1A683FFE66836491AF36BE1D3FE0A37F59DAE.der"), // SSL.com Document Signing ECC Root CA 2022
    include_bytes!("../roots/3E48813E1F94CE3ACB726F7E897FD9D868F4EC15.der"), // emSign Root Client Auth CA - G3
    include_bytes!("../roots/3F0FEB17A7EF5804CFD90A77B7BB021EA69C6418.der"), // BYTE Root Certification Authority 001
    include_bytes!("../roots/40B331A0E9BFE855BC3993CA704F4EC251D41D8F.der"), // Symantec Class 2 Public Primary Certification Authority - G6
    include_bytes!("../roots/424AAE6D0C8C7624817CDB9CCB510DED6232191D.der"), // Entrust P384 TLS Root CA - 2022
    include_bytes!("../roots/4313BB96F1D5869BC14E6A92F6CFF63469878237.der"), // TeliaSonera Root CA v1
    include_bytes!("../roots/461FDD19E71CD4329AADF224DC8C8628CD10FAE8.der"), // I.CA Root CA_RSA 05_2022
    include_bytes!("../roots/465B26BEBE7106DD8544C1139D9FA25700C1D7BD.der"), // GLOBALTRUST 2015
    include_bytes!("../roots/46AF7A31B599460D469D6041145B13651DF9170A.der"), // MULTICERT Root Certification Authority 01
    include_bytes!("../roots/46C6900A773AB6BCF465ADACFCE3F707006EDE6E.der"), // HARICA Client RSA Root CA 2021
    include_bytes!("../roots/47BEABC922EAE80E78783462A79F45C254FDE68B.der"), // Go Daddy Root Certificate Authority – G2
    include_bytes!("../roots/4812BD923CA8C43906E7306D2796E6A4CF222E7D.der"), // QuoVadis Root CA 3 G3
    include_bytes!("../roots/490A7574DE870A47FE58EEF6C76BEBC60B124099.der"), // Buypass Class 2 Root CA
    include_bytes!("../roots/4ABDEEEC950D359C89AEC752A12C5B29F6D6AA0C.der"), // Global Chambersign Root - 2008
    include_bytes!("../roots/4ACADAB14B74BF4FBA7BACE64B91801C44B8CC66.der"), // Autoridade Certificadora Raiz Brasileira v5
    include_bytes!("../roots/4B6BD2D3884E46C80CE2B962BC598CD9D5D84013.der"), // OATI WebCARES Root CA
    include_bytes!("../roots/4CDD51A3D1F5203214B0C6C532230391C746426D.der"), // SSL.com EV Root Certification Authority ECC
    include_bytes!("../roots/4EB6D578499B1CCF5F581EAD56BE3D9B6744A5E5.der"), // VeriSign
    include_bytes!("../roots/503006091D97D4F5AE39F7CBE7927D7D652D3431.der"), // Entrust (2048)
    include_bytes!("../roots/51501FBFCE69189D609CFAF140C576755DCC1FDF.der"), // Hotspot 2.0 Trust Root CA - 03
    include_bytes!("../roots/517F611E29916B5382FB72E744D98DC3CC536D64.der"), // Symantec Class 1 Public Primary Certification Authority - G6
    include_bytes!("../roots/53A2B04BCA6BD645E6398A8EC40DD2BF77C3A290.der"), // GlobalSign Root R46
    include_bytes!("../roots/5463283B6793FF55277CEDE39098E80422F912F7.der"), // AC Raíz Certicámara S.A.
    include_bytes!("../roots/54D3ACB3BD5756F6859DCEE5C321E2D4AD83D093.der"), // Telekom Security TLS RSA Root 2023
    include_bytes!("../roots/559BBA7B0FFE80D6D3829B1FD07AA4D322194790.der"), // CAEDICOM ROOT
    include_bytes!("../roots/55A6723ECBF2ECCDC3237470199D2ABE11E381D1.der"), // T-TeleSec Global Root Class 3
    include_bytes!("../roots/58A2D0EC2052815BC1F3F86402244EC28E024B02.der"), // Hongkong Post Root CA 3
    include_bytes!("../roots/58E8ABB0361533FB80F79B1B6D29D3FF8D5F00F0.der"), // D-TRUST Root Class 3 CA 2 2009
    include_bytes!("../roots/590D2D7D884F402E617EA562321765CF17D894E9.der"), // T-TeleSec GlobalRoot Class 2
    include_bytes!("../roots/5922A1E15AEA163521F898396A4646B0441B0FA9.der"), // OISTE WISeKey Global Root GA CA
    include_bytes!("../roots/5A8CEF45D7A69859767A8C8B4496B578CF474B1A.der"), // Amazon Root CA 2
    include_bytes!("../roots/5B27E1E3C91FD30E6E6EE66EDFED12F5BCDF9236.der"), // QuoVadis SMIME ECC P384 Root G4
    include_bytes!("../roots/5BC5ADE29AA754DA848953A5FED75B4686D05708.der"), // DigiCert SMIME RSA4096 Root G5
    include_bytes!("../roots/5F3B8CF2F810B37D78B4CEEC1919C37334B9C774.der"), // SECOM Trust Systems Co Ltd.
    include_bytes!("../roots/5FB7EE0633E259DBAD0C4C9AE6D38F1A61C7DC25.der"), // DigiCert
    include_bytes!("../roots/612556DA6294E5AEB33CF811BDB1DCF8A5D8B3E4.der"), // Atos TrustedRoot Root CA ECC G2 2020
    include_bytes!("../roots/61DB8C2159690390D87C9C128654CF9D3DF4DD07.der"), // D-TRUST EV Root CA 1 2020
    include_bytes!("../roots/61EF43D77FCAD46151BC98E0C35912AF9FEB6311.der"), // VeriSign
    include_bytes!("../roots/6202BF169AF27FA67ED0CEC66B782B83226126E9.der"), // Fina Root CA
    include_bytes!("../roots/6252DC40F71143A22FDE9EF7348E064251B18118.der"), // Certum
    include_bytes!("../roots/634014AEB1B0CFB2C85C93CB4C296B6ADB89315A.der"), // IdenTrust Commercial Root Client-Auth ECC CA 2
    include_bytes!("../roots/65F9901C549C9BEC6BF422B7FD8EE382F626186B.der"), // MOIS SSL Root CA
    include_bytes!("../roots/66F2DCFB3F814DDEE9B3206F11DEFE1BFBDFE132.der"), // Thailand National Root Certification Authority - G1
    include_bytes!("../roots/67650DF17E8E7E5B8240A4F4564BCFE23D69C6F0.der"), // Chunghwa Telecom Co. Ltd.
    include_bytes!("../roots/6969562E4080F424A1E7199F14BAF3EE58AB6ABB.der"), // Google Trust Services - GlobalSign ECC Root CA - R4
    include_bytes!("../roots/6A92E4A8EE1BEC964537E3295749CD96E3E5D260.der"), // HiPKI Root CA - G1
    include_bytes!("../roots/6BA0B098E171EF5AADFE4815807710F4BD6F0B28.der"), // GlobalSign
    include_bytes!("../roots/6C155ED7271A904A0DC040F0C857FF53BF6DB290.der"), // Autoridade Certificadora Raiz Brasileira v10
    include_bytes!("../roots/6C7CCCE7D4AE515F9908CD3FF6E8C378DF6FEF97.der"), // D-TRUST Root CA 3 2013
    include_bytes!("../roots/6F62DEB86C85585AE42E478DB4D76DB367585AE6.der"), // ANCERT Certificados Notariales V2
    include_bytes!("../roots/6F9AD5D5DFE82CEBBE3707EE4F4F52582941D1FE.der"), // e-Szigno TLS Root CA 2023
    include_bytes!("../roots/6FE0E6066C8BB5E49721F3F88D515A3B16737347.der"), // QuoVadis Client ECC P384 Root G4
    include_bytes!("../roots/702723132527203947E0A97829A0731372B03917.der"), // I.CA Root CA_ECC 05_2022
    include_bytes!("../roots/724DEE8119339DC8E8B1A234444115D35EAD0488.der"), // IdenTrust Commercial Root Client-Auth RSA CA 2
    include_bytes!("../roots/73A5E64A3BFF8316FF0EDCCC618A906E4EAE4D74.der"), // Microsoft RSA Root Certificate Authority 2017
    include_bytes!("../roots/73FE922F836391FFC8C6C4DAD6202F6B072E7F1B.der"), // TWCA Global Root CA G2
    include_bytes!("../roots/743AF0529BD032A0F44A83CDD4BAA97B7C2EC49A.der"), // SSL.com EV Root Certification Authority RSA R2
    include_bytes!("../roots/746F88F9AC163C53009EEF920C4067756A15717E.der"), // Swedish Government Root Authority v3
    include_bytes!("../roots/7612ED9E49B365B4DAD3120C01E603748DAE8CF0.der"), // GPKIRootCA1
    include_bytes!("../roots/7618D1F380243D5240C6116AAD5777097D8130A0.der"), // GlobalSign Secure Mail Root R45
    include_bytes!("../roots/77D30367B5E00C15F60C3861DF7CE13B92464D47.der"), // GTS Root R4
    include_bytes!("../roots/786A74AC76AB147F9C6A3050BA9EA87EFE9ACE3C.der"), // Chambers of Commerce Root - 2008
    include_bytes!("../roots/7A1F222D72B2C3198744DB6169E8A64BD70D440E.der"), // SECOM TLS ECC Root CA 2024
    include_bytes!("../roots/7A221E3DDE1B06AC9EC84770168E3CE5F76B06F4.der"), // SecureSign Root CA12
    include_bytes!("../roots/7E04DE896A3E666D00E687D33FFAD93BE83D349E.der"), // DigiCert Global Root G3
    include_bytes!("../roots/7EB1A0429BE5F428AC2B93971D7C8448A536070C.der"), // ANCERT Certificados CGN V2
    include_bytes!("../roots/807B1D9D65723DC756F9ECC5008349F6F2ACF486.der"), // SSL.com Client ECC Root CA 2022
    include_bytes!("../roots/8094640EB5A7A1CA119C1FDDD59F810263A7FBD1.der"), // GlobalSign Root CA - R6
    include_bytes!("../roots/82EF4C64F057CA0038F0DB5B76C24B654D7CDA78.der"), // Visa Public RSA Root CA
    include_bytes!("../roots/8351509B7DF8CFE87BAE62AEB9B03A52F4E62C79.der"), // Saudi National Root CA
    include_bytes!("../roots/83E5E5DE325414970B263011084456E5FAA13FFA.der"), // I.CA TLS Root CA_RSA 05_2022
    include_bytes!("../roots/8782C6C304353BCFD29692D2593E7D44D934FF11.der"), // Trustwave
    include_bytes!("../roots/87B8E6D38F1A39CD97F04A9E174B3C9EE7EE1115.der"), // DigiCert RSA4096 Root G5
    include_bytes!("../roots/87E73E149246AA634308E3A3142B1417F00FE25D.der"), // NAVER Cloud Trust Services ECC Root G1
    include_bytes!("../roots/893F6F1CE24D7FFBC3D3147A0580A7DEE10A5E4D.der"), // Telekom Security SMIME RSA Root 2023
    include_bytes!("../roots/89D483034F9E9A48805F7237D4A9A6EFCB7C1FD1.der"), // e-Szigno Root CA 2017
    include_bytes!("../roots/89DF74FE5CF40F4A80F9E3377D54DA91E101318E.der"), // MicroSec e-Szigno Root CA 2009
    include_bytes!("../roots/8A2FAF5753B1B0E6A104EC5B6A69716DF61CE284.der"), // E-Tugra Global Root CA ECC v3
    include_bytes!("../roots/8AC7AD8F73AC4EC1B5754DA540F4FCCF7CB58E8C.der"), // emSign Root CA - G1
    include_bytes!("../roots/8CF427FD790C3AD166068DE81E57EFBB932272D4.der"), // Entrust.net
    include_bytes!("../roots/8DA7F965EC5EFC37910F1C6E59FDC1CC6A6EDE16.der"), // Amazon Root CA 1
    include_bytes!("../roots/8F6BF2A9274ADA14A0C4F48E6127F9C01E785DD1.der"), // NAVER Global Root Certification Authority
    include_bytes!("../roots/912198EEF23DCAC40939312FEE97DD560BAE49B1.der"), // DigiCert Global Root CA
    include_bytes!("../roots/9152D077FEF058914009BB4C0E42A710A38238AF.der"), // CCA India 2022 SPL
    include_bytes!("../roots/91C6D6EE3E8AC86384E548C299295C756C817B81.der"), // thawte
    include_bytes!("../roots/925A8F8D2C6D04E0665F596AFF22D863E8256F3F.der"), // Amazon Services Root Certificate Authority -- G2
    include_bytes!("../roots/93057A8815C64FCE882FFA9116522878BC536417.der"), // ACCVRAIZ1
    include_bytes!("../roots/96C91B0B95B4109842FAD0D82279FE60FAB91683.der"), // D-TRUST Root Class 3 CA 2 EV 2009
    include_bytes!("../roots/999A64C37FF47D9FAB95F14769891460EEC4C3C5.der"), // Microsoft ECC Root Certificate Authority 2017
    include_bytes!("../roots/9A44497632DBDEFAD0BCFB5A7B17BD9E56092494.der"), // GTS Root R2
    include_bytes!("../roots/9B0959898154081BF6A90E9B9E58A4690C9BA104.der"), // I.CA Root CA_RSA
    include_bytes!("../roots/9BAAE59F56EE21CB435ABE2593DFA7F040D11DCB.der"), // SwissSign Silver G2 Root CA
    include_bytes!("../roots/9CB1E6FBC21AAF3D68973CB516E932C44CB9D560.der"), // Visa Public ECC Root CA
    include_bytes!("../roots/9D319381546EA6A12811E09CF90A20C840BE944D.der"), // eSignTrust Root Certification Authority (G03)
    include_bytes!("../roots/9D70BB01A5A4A018112EF71C01B932C534E788A8.der"), // Certinomis - Root CA
    include_bytes!("../roots/9EBC751042B302F381F4F73062D48FC3A751B2DD.der"), // Atos TrustedRoot Root CA ECC TLS 2021
    include_bytes!("../roots/9F5FD91A546DF50C71F0EE7ABD1749988473E239.der"), // SSL.com TLS ECC Root CA 2022
    include_bytes!("../roots/9F744E9F2B4DBAEC0F312C50B6563B8E2D93C311.der"), // Sectigo (formerly Comodo CA) ECC
    include_bytes!("../roots/9FF1718D92D59AF37D7497B4BC6F84680BBAB666.der"), // Hellenic Academic and Research Institutions ECC RootCA 2015
    include_bytes!("../roots/A14B48D943EE0A0E40904F3CE0A4C09193515D3F.der"), // DigiCert Assured ID Root G2
    include_bytes!("../roots/A1585187156586CEF9C454E22AB15C58745607B4.der"), // Swiss Government Root CA I
    include_bytes!("../roots/A2BEE4AD032713ADCE0A0E9B19B6B85FC24ECA8D.der"), // GlobalSign Client Authentication Root E45
    include_bytes!("../roots/A3A1B06F2461234AE336A5C237FCA6FFDDF0D73A.der"), // UCA Extended Validation Root
    include_bytes!("../roots/A4D6B770E765A9BF17ECD7B5E03B852D612FA71D.der"), // AC RAIZ FNMT-RCM G2
    include_bytes!("../roots/A55BD8476C8F19F74CF46D6BB6C2798222DF548B.der"), // D-TRUST EV Root CA 2 2023
    include_bytes!("../roots/A78849DC5D7C758C8CDE399856B3AAD0B2A57135.der"), // DigiCert TLS RSA4096 Root G5
    include_bytes!("../roots/A79E41380BAB3ED7F5188D9A5209CEFCB3CA6991.der"), // CCA India 2022
    include_bytes!("../roots/A8985D3A65E5E5C4B2D7D66D40C6DD2FB19C5436.der"), // DigiCert
    include_bytes!("../roots/A9CAFE9DFD67F4145AD397D0E2F3050D198DE6EE.der"), // Australian Defence Public Root CA
    include_bytes!("../roots/AA40D2579BA82424CD27719B1D6B1F3571738099.der"), // PostSignum Root QCA 4
    include_bytes!("../roots/AA5970E520329FCBD0D5799FFB1B821DFD1F7965.der"), // SSL.com Client RSA Root CA 2022
    include_bytes!("../roots/AA6C3CAFF096C64DC32784BE9D8A3E3A7BB44EC2.der"), // Telia RSA Email Root CA v3
    include_bytes!("../roots/AD7E1C28B064EF8F6003402014C3D0E3370EB58A.der"), // Starfield Class 2 Certification Authority
    include_bytes!("../roots/AD98F9F3E47D753B65D482B3A45217BB6EF5E438.der"), // Sectigo Public Server Authentication Root R46
    include_bytes!("../roots/AE3B31BF8FD891079CF1DF34CBCE6E70D37FB5B0.der"), // ComSign Global Root CA
    include_bytes!("../roots/AEA67D05749B734B826D2809BAD62C3C45C03B0A.der"), // Telia EC Client Root CA v3
    include_bytes!("../roots/AEC5FB3FC8E1BFC4E54F03075A9AE800B7F7B6FA.der"), // CAROOT Firmaprofesional
    include_bytes!("../roots/AFE5D244A8D1194230FF479FE2F897BBCD7A8CB4.der"), // Sectigo (formerly Comodo CA)
    include_bytes!("../roots/B12E13634586A46F1AB2606837582DC4ACFD9497.der"), // Certigna
    include_bytes!("../roots/B1BC968BD4F49D622AA89A81F2150152A41D829C.der"), // GlobalSign Root CA - R1
    include_bytes!("../roots/B1C3AC0977AAF147E5821A87F8DA32226A210693.der"), // Notarius Root Certificate Authority
    include_bytes!("../roots/B2142AA969EB0DDB5CE9024684CD850B69E418E5.der"), // DVV Gov. Root CA - G3 ECC
    include_bytes!("../roots/B218FE6D07952A2207A35AFD5ED8E4991029E336.der"), // DigiCert Client ECC P384 Root G5
    include_bytes!("../roots/B31EB1B740E36C8402DADC37D44DF5D4674952F9.der"), // Entrust
    include_bytes!("../roots/B49082DD450CBE8B5BB166D3E2A40826CDED42CF.der"), // Trustwave Global ECC P256 Certification Authority
    include_bytes!("../roots/B51C067CEE2B0C3DF855AB2D92F4FE39D4E70F0E.der"), // Starfield Root Certificate Authority – G2
    include_bytes!("../roots/B561EBEAA4DEE4254B691A98A55747C234C7D971.der"), // CA Disig Root R2
    include_bytes!("../roots/B60D92FC064D32AF1FEA30FCD85FB0243463A41C.der"), // DigiCert Client RSA4096 Root G5
    include_bytes!("../roots/B6AF43C29B81537DF6EF6BC31F1F60150CEE4866.der"), // emSign ECC Root CA - C3
    include_bytes!("../roots/B6BF372A3689B35699F09913DA011D73A6E10FCE.der"), // QuoVadis TLS ECC P384 Root G4
    include_bytes!("../roots/B7AB3308D1EA4477BA1480125A6FBDA936490CBB.der"), // SSL.com Root Certification Authority RSA
    include_bytes!("../roots/B7F91D98EC2593F35014849AA87E22103CC43927.der"), // Telekom Security SMIME ECC Root 2021
    include_bytes!("../roots/B80186D1EB9C86A54104CF3054F34C52B7E558C6.der"), // Trustwave
    include_bytes!("../roots/B80E26A9BFD2B23BC0EF46C9BAC7BBF61D0D4141.der"), // Security Communication ECC RootCA1
    include_bytes!("../roots/B8236B002F1D16865301556C11A437CAEBFFC3BB.der"), // AffirmTrust Premium ECC
    include_bytes!("../roots/B8B1C5AAC29BEDF0AD71B2F14BFEAA38F817535E.der"), // Entrust SMIME Root CA - 2022
    include_bytes!("../roots/B999CDD173508AC44705089C8C88FBBEA02B40CD.der"), // Telia Root CA v2
    include_bytes!("../roots/BA29416077983FF4F3EFF231053B2EEA6D4D45FD.der"), // IdenTrust Public Sector Root CA 1
    include_bytes!("../roots/BCB0C19DE9989270193857E98DA7B45D6EEE0148.der"), // HARICA TLS ECC Root CA 2021
    include_bytes!("../roots/BDB1B93CD5978D45C6261455F8DB95C75AD153AF.der"), // ISRG Root X2
    include_bytes!("../roots/BE64D3DA144BD26BCDAF8FDBA6A672F8DE26F900.der"), // HARICA Client ECC Root CA 2021
    include_bytes!("../roots/C0F896C5A93B01062107DA184248BCE99D88D5EC.der"), // Telekom Security TLS ECC Root 2020
    include_bytes!("../roots/C303C8227492E561A29C5F79912B1E441391303A.der"), // Security Communication RootCA3
    include_bytes!("../roots/C3197C3924E654AF1BC4AB20957AE2C30E13026A.der"), // SSL.com Root Certification Authority ECC
    include_bytes!("../roots/C4DA90EE324D7E4D041CB1F286FBB45388207CA1.der"), // NAVER Cloud Trust Services RSA Root G1
    include_bytes!("../roots/C7E21E0142321739B99F1002FAF377B63513E63F.der"), // Telia RSA Client Root CA v3
    include_bytes!("../roots/C88344C018AE9FCCF187B78F22D1C5D74584BAE5.der"), // Certum Trusted Root CA
    include_bytes!("../roots/C9B8DBF79C9A3D54B7E46EE63D72F9435E32BFA6.der"), // QuoVadis SMIME RSA 4096 Root G4
    include_bytes!("../roots/CA3AFBCF1240364B44B216208880483919937CF7.der"), // QuoVadis Root CA 2
    include_bytes!("../roots/CABD2A79A1076A31F21D253635CB039D4329A5E8.der"), // ISRG Root X1
    include_bytes!("../roots/CB658264EA8CDA186E1752FB52C397367EA387BE.der"), // Echoworx Root CA2
    include_bytes!("../roots/CBBA83C8C15A5DF1F9736FCAD7EF2813064A077D.der"), // SecureSign Root CA15
    include_bytes!("../roots/CF9E876DD3EBFC422697A3B5A37AA076A9062348.der"), // TWCA Root Certification Authority 1
    include_bytes!("../roots/CFE970840FE0730F9DF60C7F2C4BEE2046349CBB.der"), // TunTrust Root CA
    include_bytes!("../roots/D05849DE4004DA6E867DEE000671CDA8F423266F.der"), // A-Trust-Root-09
    include_bytes!("../roots/D067C11351010CAAD0C76A65373116264F5371A2.der"), // GLOBALTRUST 2020
    include_bytes!("../roots/D1CBCA5DB2D52A7F693B674DE5F05A1D0C957DF0.der"), // Sectigo ECC
    include_bytes!("../roots/D1EB23A46D17D68FD92564C2F1F1601764D8E349.der"), // Sectigo (AAA)
    include_bytes!("../roots/D1EEB1E8C09020BAB85D3DE27F78EE33A06CAEDB.der"), // DigiCert ECC P384 Root G5
    include_bytes!("../roots/D273962A2A5E399F733FE1C71E643F033834FC4D.der"), // GTS Root R2
    include_bytes!("../roots/D37B8B0AE84244FB6B8038EEAE9180261A487066.der"), // Sectigo Public Email Protection Root R46
    include_bytes!("../roots/D3DD483E2BBF4C05E8AF10F5FA7626CFD3DC3092.der"), // Certum Trusted Network CA 2
    include_bytes!("../roots/D4695284CD1798D9CB1699464C064994C4E2BBFD.der"), // SSL.com Code Signing RSA Root CA 2022
    include_bytes!("../roots/D496592B305707386CC5F3CDB259AE66D7661FCA.der"), // ACA ROOT
    include_bytes!("../roots/D69B561148F01C77C54578C10926DF5B856976AD.der"), // GlobalSign Root CA - R3
    include_bytes!("../roots/D8A6332CE0036FB185F6634F7D6A066526322827.der"), // AffirmTrust Premium
    include_bytes!("../roots/D8C5388AB7301B1B6ED47AE645253A6F9F1A2761.der"), // SwissSign
    include_bytes!("../roots/D8EB6B41519259E0F3E78500C03DB68897C9EEFC.der"), // Government of Netherlands G3
    include_bytes!("../roots/D99B104298594763F0B9A927B79269CB47DD158B.der"), // ePKI Root Certification Authority - G2
    include_bytes!("../roots/DAFAF7FA6684EC068F1450BDC7C281A5BCA96457.der"), // Buypass Class 3 Root CA
    include_bytes!("../roots/DC775C1C874F1BBF51099F6FB129DB99FF08EB52.der"), // GlobalSign Client Authentication Root R45
    include_bytes!("../roots/DD50C0F779B3642E74A2B89D9FD340DDBBF0F24F.der"), // SecureSign Root CA14
    include_bytes!("../roots/DDFB16CD4931C973A2037D3FC83A4D7D775D05E4.der"), // DigiCert Trusted Root G4
    include_bytes!("../roots/DE010808E41EC41930D44095F8FE596B582C8CA2.der"), // Hongkong Post Root CA 2
    include_bytes!("../roots/DF3C24F9BFD666761B268073FE06D1CC8D4F82A4.der"), // DigiCert Global Root G2
    include_bytes!("../roots/DF717EAA4AD94EC9558499602D48DE5FBCF03A25.der"), // IdenTrust Commercial Root CA 1
    include_bytes!("../roots/E011845E34DEBE8881B99CF61626D1961FC3B931.der"), // OISTE WISeKey Global Root GC CA
    include_bytes!("../roots/E1C950E6EF22F84C5645728B922060D7D5A7A3E8.der"), // GTS Root R1
    include_bytes!("../roots/E252FA953FEDDB2460BD6E28F39CCCCF5EB33FDE.der"), // SZAFIR ROOT CA2
    include_bytes!("../roots/E2B8294B5584AB6B58C290466CAC3FB8398F8483.der"), // CFCA EV ROOT
    include_bytes!("../roots/E58C1CC4913B38634BE9106EE3AD8E6B9DD9814A.der"), // GTS Root R1
    include_bytes!("../roots/E72EF1DFFCB20928CF5DD4D56737B151CB864F01.der"), // emSign Root CA - C1
    include_bytes!("../roots/E7F3A3C8CF6FC3042E6D0E6732C59E68950D5ED2.der"), // Trustwave Global ECC P384 Certification Authority
    include_bytes!("../roots/E9A85D2214521C5BAA0AB4BE246A238AC9BAE2A9.der"), // E-Tugra Global Root CA RSA v3
    include_bytes!("../roots/EADB0AB9DC7938021435FED13E488406A1AA292A.der"), // Entrust 4K EV TLS Root CA - 2022
    include_bytes!("../roots/EAF83D8427897576CDD1B30957773E5F74B9B7CC.der"), // DVV Gov. Root CA - G3 RSA
    include_bytes!("../roots/EB9237B72076F8CC8BC13E7046F2FCABC18199D3.der"), // Carillon PKI Services G2 Root CA 1
    include_bytes!("../roots/EC2C834072AF269510FF0EF203EE3170F6789DCA.der"), // SSL.com TLS RSA Root CA 2022
    include_bytes!("../roots/EC503507B215C4956219E2A89A5B42992C4C2C20.der"), // AC RAIZ FNMT-RCM
    include_bytes!("../roots/EC8A396C40F02EBC4275D49FAB1C1A5B67BED29A.der"), // Sectigo Public Server Authentication Root E46
    include_bytes!("../roots/EC93DE083C93D933A986B3D5CDE25ACB2FEECF8E.der"), // NetLock Platina (Class Platinum) Főtanúsítvány
    include_bytes!("../roots/ECA2D530A9AB2C7D0E7561644E0AE016A154387D.der"), // LAWtrust Root CA2 (4096)
    include_bytes!("../roots/EDE571802BC892B95B833CD232683F09CDA01E46.der"), // GTS Root R3
    include_bytes!("../roots/EE869387FFFD8349AB5AD14322588789A457B012.der"), // Sectigo (CCA)
    include_bytes!("../roots/EF00428C8BD55BF387DC3BD5599218EAE0954B07.der"), // emSign Root Client Auth CA - G1
    include_bytes!("../roots/F33E783CACDFF4A2CCAC67556956D7E5163CE1ED.der"), // Certum EC-384 CA
    include_bytes!("../roots/F373B387065A28848AF2F34ACE192BDDC78E9CAC.der"), // Actalis Authentication Root CA
    include_bytes!("../roots/F435F85F0108DA684E7BFD517C90C627BB9A6CF5.der"), // VRK Gov. Root CA - G2
    include_bytes!("../roots/F517A24F9A48C6C9F8A200269FDC0F482CAB3089.der"), // DigiCert Assured ID Root G3
    include_bytes!("../roots/F6108407D6F8BB67980CC2E244C2EBAE1CEF63BE.der"), // Amazon Root CA 4
    include_bytes!("../roots/F90CC7521EAB33F228EAA835E4E50292E31D281E.der"), // TrustFactory Client Root Certificate Authority
    include_bytes!("../roots/F9B5B632455F9CBEEC575F80DCE96E2CC7B278B7.der"), // AffirmTrust Commercial
    include_bytes!("../roots/FAB7EE36972662FB2DB02AF6BF03FDE87C4B2F9B.der"), // certSIGN Root CA
    include_bytes!("../roots/FB97967CEF8D986306C03BB611F8E01397A298D3.der"), // SECOM TLS RSA Root CA 2024
    include_bytes!("../roots/FE45659B79035B98A161B5512EACDA580948224D.der"), // Hellenic Academic and Research Institutions RootCA 2011
    include_bytes!("../roots/FF54E2961172CEDA5A4C97494F1B5D0DF0F17D6F.der"), // QuoVadis Signing ECC P384 Root G4
    include_bytes!("../roots/FFB7E08F66E1D0C2582F0245C4970292A46E8803.der"), // Főtanúsítványkiadó - Kormányzati Hitelesítés Szolgáltató
];
